source "http://gemcutter.org"
gem "rails", "2.3.5"
gem "autotest"
gem "autotest-fsevent"
gem "autotest-growl"
gem "bundler"
gem "garb"
gem "jekyll"
gem "mocha"
gem "passenger"
gem "shoulda"
gem "sqlite3-ruby"
gem "timecop"
