source "http://rubygems.org/"
gem "autotest"
gem "autotest-fsevent"
gem "autotest-growl"
gem "bundler"
gem "garb"
gem "jekyll"
gem "mocha"
gem "passenger"
gem "rails", "2.3.5"
gem "rack", "1.0.1"
gem "rubygems-update"
gem "shoulda"
gem "sqlite3-ruby"
gem "timecop"
gem "yard"
