name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mongo:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        ruby:
          - 2.3
          - 2.4
          - jruby-9.1.13.0
        db:
          - mongodb
          - redis
          - active_record
        gemfile:
          - gemfiles/rails42.gemfile
          - gemfiles/rails42_protected_attributes.gemfile
          - gemfiles/rails51.gemfile
          - gemfiles/rails52.gemfile
        exclude:
          - rvm: jruby-9.1.13.0
            gemfile: gemfiles/rails5.gemfile
    env:
      DB: ${{ matrix.db }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rake test
